run:
  timeout: 5m
  skip-files:
   - ".*generated.*\\.go"
   - external/
   - pkg/util/cloudinit/schema/

# override defaults
linters-settings:
  # gocyclo:
  #   min-complexity: 18
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/vmware-tanzu
  importas:
    alias:
      - alias: context
        pkg: context

      - alias: corev1
        pkg: k8s.io/api/core/v1
      - alias: metav1
        pkg: k8s.io/apimachinery/pkg/apis/meta/v1
      - alias: apiconversion
        pkg: k8s.io/apimachinery/pkg/conversion
      - alias: apierrors
        pkg: k8s.io/apimachinery/pkg/api/errors
      - alias: apierrorsutil
        pkg: k8s.io/apimachinery/pkg/util/errors

      - alias: ctrl
        pkg: sigs.k8s.io/controller-runtime
      - alias: ctrlcache
        pkg: sigs.k8s.io/controller-runtime/pkg/cache
      - alias: ctrlconversion
        pkg: sigs.k8s.io/controller-runtime/pkg/conversion
      - alias: ctrlclient
        pkg: sigs.k8s.io/controller-runtime/pkg/client
      - alias: ctrlmgr
        pkg: sigs.k8s.io/controller-runtime/pkg/manager

      - alias: vim25
        pkg: github.com/vmware/govmomi/vim25
      - alias: mo
        pkg: github.com/vmware/govmomi/vim25/mo
      - alias: vimtypes
        pkg: github.com/vmware/govmomi/vim25/types

      - alias: vmopv1a1
        pkg: github.com/vmware-tanzu/vm-operator/api/v1alpha1

      - alias: vmopv1a2
        pkg: github.com/vmware-tanzu/vm-operator/api/v1alpha2
      - alias: vmopv1a2cloudinit
        pkg: github.com/vmware-tanzu/vm-operator/api/v1alpha2/cloudinit
      - alias: vmopv1a2common
        pkg: github.com/vmware-tanzu/vm-operator/api/v1alpha2/common
      - alias: vmopv1a2sysprep
        pkg: github.com/vmware-tanzu/vm-operator/api/v1alpha2/sysprep

      - alias: vmopv1
        pkg: github.com/vmware-tanzu/vm-operator/api/v1alpha3
      - alias: vmopv1cloudinit
        pkg: github.com/vmware-tanzu/vm-operator/api/v1alpha3/cloudinit
      - alias: vmopv1common
        pkg: github.com/vmware-tanzu/vm-operator/api/v1alpha3/common
      - alias: vmopv1sysprep
        pkg: github.com/vmware-tanzu/vm-operator/api/v1alpha3/sysprep
      - alias: vmopv1util
        pkg: github.com/vmware-tanzu/vm-operator/pkg/util/vmopv1

      - alias: pkgcfg
        pkg: github.com/vmware-tanzu/vm-operator/pkg/config
      - alias: pkgctx
        pkg: github.com/vmware-tanzu/vm-operator/pkg/context
      - alias: pkgmgr
        pkg: github.com/vmware-tanzu/vm-operator/pkg/manager
      - alias: pkgutil
        pkg: github.com/vmware-tanzu/vm-operator/pkg/util
      - alias: proberctx
        pkg: github.com/vmware-tanzu/vm-operator/pkg/prober/context

linters:
  disable-all: true
  enable:
  - asciicheck
  - bodyclose
  - depguard
  - dogsled
  - errcheck
  - exportloopref
  - goconst
  - gocritic
  - gocyclo
  - godot
  - gofmt
  - goimports
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - misspell
  - nakedret
  - nilerr
  - nolintlint
  - prealloc
  - revive
  - rowserrcheck
  - staticcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  # Disable the default golangci exclusions so no issues are skipped. This helps
  # reviewers focus on reviewing the most relevant changes in the PRs and avoid
  # nitpicking.
  exclude-use-default: false
  exclude:
  # TODO: Remove the following exclusions over time once we have fixed those.
  - "ST1000: at least one file in a package should have a package comment"
  # List of regexps of issue texts to exclude, empty list by default.
  exclude-rules:
  - linters:
    - staticcheck
    text: "^SA1019: [^.]+.Wait is deprecated: Please use WaitEx instead."
  - linters:
    - staticcheck
    text: "^SA1019: [^.]+.WaitForResult is deprecated: Please use WaitForResultEx instead."
  - linters:
    - revive
    text: ".*should have (a package )?comment.*"
  - linters:
    - revive
    text: "^exported: comment on exported const"
  - linters:
    - staticcheck
    text: "^SA1019: .*TCPSocket is deprecated"
  # Dot imports for gomega or ginkgo are allowed within test files.
  - path: test/builder/intg_test_context.go
    text: should not use dot imports
  - path: test/builder/test_suite.go
    text: should not use dot imports
  - path: test/builder/vcsim_test_context.go
    text: should not use dot imports
  # All of our webhooks follow the pattern of passing the webhook context which
  # contains fields like the Client. Ignore the linter warnings for now.
  - path: webhooks/
    text: ".* `ctx` is unused"
  - path: _test.go
    linters:
    - gosec
  - linters:
    - revive
    text: "unused-parameter: parameter"
