- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: KUBERNETES_SERVICE_HOST
    value: "127.0.0.1"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: KUBERNETES_SERVICE_PORT
    value: "6443"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_Unified_TKG
    value: "<FSS_WCP_Unified_TKG_VALUE>"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_VMSERVICE_V1ALPHA2
    value: "<FSS_WCP_VMSERVICE_V1ALPHA2_VALUE>"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: VSPHERE_NETWORKING
    value: "<VSPHERE_NETWORKING_VALUE>"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_INSTANCE_STORAGE
    value: "<FSS_WCP_INSTANCE_STORAGE_VALUE>"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: NETWORK_PROVIDER
    value: "<NETWORK_PROVIDER_VALUE>"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_NAMESPACED_VM_CLASS
    value: "<FSS_WCP_NAMESPACED_VM_CLASS_VALUE>"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_VMSERVICE_BACKUPRESTORE
    value: "<FSS_WCP_VMSERVICE_BACKUPRESTORE_VALUE>"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: PRIVILEGED_USERS
    value: "<COMMA_SEPARATED_LIST_OF_USERS>"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_PODVMONSTRETCHEDSUPERVISOR
    value: "<FSS_PODVMONSTRETCHEDSUPERVISOR>"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_TKG_Multiple_CL
    value: "<FSS_WCP_TKG_Multiple_CL_VALUE>"